### ISSUE TITLE
Install documentation

### ISSUE THREAD

**Issue by aloysius-pgast** [Jacwutang/CryptoEngineX#11]
Hi, first it seems like an interesting project. I built an http/ws gateway which provide support for multiple exchanges (4 for now) and I wanted to test CryptoEngineX to see a possible integration. Could you indicate which steps I'm missing or which branch I should try ? I tried the following with master branch (b415278)

```
npm install
nodemon index.js
```

And got

```
index.js:1
[0] (function (exports, require, module, __filename, __dirname) { const router = require("express-promise-router").Router();
[0]                                                                                                                ^
[0] 
[0] TypeError: require(...).Router is not a function
[0]     at Object.<anonymous> (CryptoEngineX/routes/index.js:1:112)
[0]     at Module._compile (module.js:652:30)
[0]     at Object.Module._extensions..js (module.js:663:10)
[0]     at Module.load (module.js:565:32)
[0]     at tryModuleLoad (module.js:505:12)
[0]     at Function.Module._load (module.js:497:3)
[0]     at Module.require (module.js:596:17)
[0]     at require (internal/module.js:11:18)
[0]     at Object.<anonymous> (CryptoEngineX/index.js:6:15)
[0]     at Module._compile (module.js:652:30)
```

Thanks

**Comment by aloysius-pgast** [comment]
One more question. Are the images linked in the readme mockups or real screenshots ?

**Comment by aloysius-pgast** [comment]
Ok, found the pb. I had to replace
```
const router = require("express-promise-router").Router();
```
With
```
const router = require("express-promise-router")();
```

**Comment by Jacwutang** [comment]
Thanks for the issue. I will write some documentation in the upcoming weeks, I have been very busy.
